# Generated by Django 4.2.2 on 2023-07-03 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='contact',
            field=models.IntegerField(null=True),
        ),
    ]
